apiVersion: v1
kind: Pod
metadata:
  name: spring-mvc-ilia
  namespace: test
  labels:
    app: spring-mvc-ilia
spec:
  containers:
  - name: spring-mvc-ilia
    image: shashkist/springmvc1

---
apiVersion: v1
kind: Service
metadata:
  name: spring-mvc-service
  namespace: test
spec:
  type: LoadBalancer
  selector:
    app: spring-mvc-ilia
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30001